Console.Clear();
Console.Write("Какое число больше...?\nВведите первое число: ");
int a = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите второе число: ");
int b = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите третье число: ");
int c = Convert.ToInt32(Console.ReadLine());
int d = a > b ? a : b;
d = d > c ? d : c;
Console.WriteLine($"Из трёх чисел {a}, {b} и {c} большим является {d}");
